export const STR = {
  title: "FonoMundo — Bosque de los Sonidos",
  start: "¡Jugar!",
  hint_move: "WASD / flechas — mover · arrastrar ratón — mirar",
  hint_gather: "E — explorar fonema / sílaba / palabra",
  hint_eat: "F — usar palabra",
  hint_build: "1 taller · 2 cadena · 3 diario",
  hud_wood: "Fonemas",
  hud_stone: "Sílabas",
  hud_berries: "Palabras",
  hud_hunger: "Motivación",
  hud_warmth: "Concentración",
  hud_day: "Sesión",
  hud_time: "Tiempo",
  msg_need_wood: "Necesitas más fonemas",
  msg_need_stone: "Necesitas más sílabas",
  msg_built_fire: "¡Taller activo! — quédate cerca para concentrarte",
  msg_built_wall: "¡Cadena fonémica construida!",
  msg_built_chest: "¡Diario de palabras colocado!",
  msg_ate: "¡Usaste una palabra! ¡Bien!",
  msg_no_berries: "No tienes palabras todavía",
  msg_starving: "¡Tu motivación baja! Explora más.",
  msg_freezing: "¡Pierdes concentración! Activa un taller.",
  msg_dawn: "¡Superaste la sesión! Empieza una nueva.",
  msg_dead: "¡Descansamos un momento! Volviendo al inicio...",
  build_fire: "Taller",
  build_wall: "Cadena",
  build_chest: "Diario",
  prompt_chop: "Explorar fonema (E)",
  prompt_mine: "Segmentar sílaba (E)",
  prompt_forage: "Leer palabra (E)",
  mobile_gather: "EXPLORAR",
  mobile_eat: "USAR",
  paused: "Pausado — clic para continuar"
};
