export const STICK_CONFIG = {
  numberedCount: 22,
  kaboomCount: 4,
};

export const LEVELS = {
  INITIAL: "Inicial",
  ADVANCED: "Avanzado",
};

export const GAME_STATES = {
  PLAYING: "Playing",
  FINISHED: "Finished",
};

export const INITIAL_BOARD = [
  "Dibuja la frase",
  "Lee como si…",
  "Escribe la palabra",
  "Imita con gestos",
  "Di palabra que empiece por…",
  "Lee como si…",
  "Escribe la palabra",
  "Lee como si…",
  "Imita con gestos",
  "Lee como si…",
  "Escribe la palabra",
  "Di palabra que empiece por…",
  "Imita con gestos",
  "Lee como si…",
  "Dibuja la frase",
  "Lee como si…",
  "Di palabra que empiece por…",
  "Escribe la palabra",
  "Imita con gestos",
  "Di palabra que empiece por…",
  "Escribe la palabra",
  "Di palabra que empiece por…",
];

export const ADVANCED_BOARD = [
  "Corrige la oración",
  "Lee como si…",
  "Escribe oración (palabras obligatorias)",
  "Representa con gestos",
  "Explica sin palabras prohibidas",
  "Lee como si…",
  "Escribe oración",
  "Corrige la oración",
  "Representa con gestos",
  "Lee como si…",
  "Escribe oración",
  "Explica sin palabras prohibidas",
  "Representa con gestos",
  "Lee como si…",
  "Corrige la oración",
  "Lee como si…",
  "Explica sin palabras prohibidas",
  "Escribe oración",
  "Representa con gestos",
  "Explica sin palabras prohibidas",
  "Escribe oración",
  "Corrige la oración",
];

export const INITIAL_DATABASE = {
  writeWord: [
    "Piña",
    "Manzana",
    "Plátano",
    "Uvas",
    "Maleta",
    "Flor",
    "Ola",
    "Bañador",
    "Tijeras",
    "Corona",
    "Zapatillas",
    "Oso",
    "Cactus",
    "Sol",
    "Sopa",
    "Seta",
    "Paloma",
    "Gato",
    "Hueso",
    "Regalo",
    "Llave",
    "Tambor",
    "Silla",
    "Serpiente",
  ],
  gesture: [
    "Gato",
    "Serpiente",
    "Conejo",
    "León",
    "Perro",
    "Pájaro",
    "Ola",
    "Oso",
    "Avión",
    "Coche",
    "Moto",
    "Ambulancia",
    "Ratón",
    "Gusano",
    "Mariposa",
    "Elefante",
  ],
  drawPhrase: [
    "La nube está detrás del sol",
    "El gato es marrón",
    "El bebé coge el biberón",
    "Tengo tres lápices de colores",
    "Dos perros jugando",
    "La niña está leyendo un libro",
    "El ratón come queso",
    "Un cuadrado de color verde",
    "El sol está sonriendo",
    "La luna está triste",
    "La flor es azul",
    "Tengo una moneda de 2€",
    "El delfín azul",
    "Un payaso de pelo rojo",
    "Un ratón sonriendo",
    "Unas cerezas rojas",
  ],
  startsWithSets: [
    ["a", "b", "c", "d", "e", "f", "g", "h"],
    ["i", "j", "k", "l", "ll", "m", "n", "ñ"],
    ["o", "p", "q", "r", "s", "t", "u", "v"],
    ["w", "x", "y", "z"],
  ],
};

export const READ_AS_IF = [
  "Fueras un ROBOT",
  "Tuvieras mucho FRÍO",
  "Estuvieras ENFADADO/A",
  "Estuvieras TRISTE",
  "Estuvieras CANTANDO",
  "Tuvieras MIEDO",
  "Tuvieras la boca llena de AIRE",
  "Estuvieras MUY FELIZ",
  "Estuvieras en CÁMARA LENTA",
  "Fueras un MAGO",
  "Estuvieras contando un SECRETO",
  "Fueras un MONSTRUO",
  "Estuvieras nervioso/a",
  "Tuvieras mucha PRISA",
  "Estuvieras cansado/a",
  "Fueras un BEBÉ",
  "Fueras presentador/a de TELEVISIÓN",
  "Acabaras de ganar un PREMIO",
  "Fueras un/a REY/REINA",
  "Estuvieras dando una ORDEN",
  "Pidieras AYUDA",
];

export const ADVANCED_DATABASE = {
  requiredWords: [
    ["amigo", "colegio", "recreo", "familia"],
    ["nervioso", "enfadado"],
    ["leer", "escribir"],
    ["compartir", "flor", "sol"],
    ["libro", "mesa"],
    ["pelota", "bicicleta", "uniforme"],
    ["desayuno", "merienda", "excursión"],
    ["temprano", "paciencia", "respeto", "viaje", "ciudad"],
    ["montaña", "chocolate", "lluvia", "agua", "móvil", "cargar"],
    ["gato", "ventana"],
    ["noche", "ruido"],
    ["cena", "familia"],
    ["robot", "escoba"],
  ],
  correctSentence: [
    "Mis amigos estaba cansado despues del partido.",
    "Yo hize los deberes antes de cenar.",
    "Mi perro y mi gato es muy travieso.",
    "El arbol del patio es muy grande.",
    "Cuando vienes a jugar a mi casa.",
    "No se porque no vinistes ayer.",
    "El profesor nos dijo que mañana abra examen.",
    "Mi hermana no sabe donde a dejado el libro.",
    "Ayer los niño jugaba en el patio del colegio.",
    "Habian muchos pájaros en los arbol del jardin.",
    "Los alumnos fue al museo con su profesora.",
    "Mi mama preparo una tarta para mi cumpleaños.",
    "Ayer llovia mucho y no pudimos salir a fuera.",
    "El profesor nos esplico el ejercicio.",
    "Pedro y su amigo encontro un tesoro en el bosque.",
    "La niña estaba contenta porque gano el partido.",
    "El jefe dijo que vayamos temprano ayer.",
    "Ayer llovió mucho y hubieron muchos charcos.",
    "Mi hermano me dijo de que vendría mas tarde.",
    "El profesor nos explicó que la clima iba a cambiar.",
    "La mujer que ví ayer eran mis vecinas.",
    "Ojalá que tu me hubieras dicho la verdad antes.",
    "No se porque no me contestastes el mensaje.",
    "Habían muchas personas en la fiesta.",
  ],
  explainWithoutForbidden: [
    { concept: "Planeta", forbidden: "Tierra" },
    { concept: "Volcán", forbidden: "Lava" },
    { concept: "Democracia", forbidden: "Votar" },
    { concept: "Sustantivo", forbidden: "Nombre" },
    { concept: "Energía", forbidden: "Electricidad" },
    { concept: "Imán", forbidden: "Nevera" },
    { concept: "Ecosistema", forbidden: "Naturaleza" },
    { concept: "Fracción", forbidden: "Mitad" },
    { concept: "Saltar", forbidden: "Brincar" },
    { concept: "Cocinar", forbidden: "Comida" },
    { concept: "Teléfono", forbidden: "Llamar" },
    { concept: "Reloj", forbidden: "Hora" },
    { concept: "Médico", forbidden: "Hospital" },
    { concept: "Peluquero", forbidden: "Pelo" },
    { concept: "Despertador", forbidden: "Sonar" },
    { concept: "Lluvia", forbidden: "Agua" },
    { concept: "Susurrar", forbidden: "Hablar" },
    { concept: "Reflexionar", forbidden: "Pensar" },
    { concept: "Microscopio", forbidden: "Pequeño" },
    { concept: "Camaleón", forbidden: "Color" },
    { concept: "Medusa", forbidden: "Mar" },
    { concept: "Empatía", forbidden: "Sentir" },
    { concept: "Hornear", forbidden: "Horno" },
    { concept: "Aplaudir", forbidden: "Manos" },
  ],
  advancedGesture: [
    "Pingüino",
    "Astronauta",
    "Mago/a",
    "Robot",
    "Chef",
    "Payaso/a",
    "Murciélago",
    "Vampiro",
    "Médico",
    "Profesor/a",
    "Futbolista",
    "Peluquero/a",
    "Cantante",
    "Fotógrafo/a",
    "Perro",
    "Delfín",
    "Rana",
    "Serpiente",
    "Mono",
    "Caballo",
    "Princesa",
    "Superhéroe/Superheroína",
    "Fantasma",
    "Ninja",
  ],
};

export const SLOT_TYPE = {
  DRAW_PHRASE: "DRAW_PHRASE",
  READ_AS_IF: "READ_AS_IF",
  WRITE_WORD: "WRITE_WORD",
  GESTURE_INITIAL: "GESTURE_INITIAL",
  STARTS_WITH: "STARTS_WITH",
  CORRECT_SENTENCE: "CORRECT_SENTENCE",
  WRITE_SENTENCE_REQUIRED: "WRITE_SENTENCE_REQUIRED",
  WRITE_SENTENCE: "WRITE_SENTENCE",
  GESTURE_ADVANCED: "GESTURE_ADVANCED",
  EXPLAIN_WITHOUT_FORBIDDEN: "EXPLAIN_WITHOUT_FORBIDDEN",
};

export const INITIAL_SLOT_TYPES = [
  SLOT_TYPE.DRAW_PHRASE,
  SLOT_TYPE.READ_AS_IF,
  SLOT_TYPE.WRITE_WORD,
  SLOT_TYPE.GESTURE_INITIAL,
  SLOT_TYPE.STARTS_WITH,
  SLOT_TYPE.READ_AS_IF,
  SLOT_TYPE.WRITE_WORD,
  SLOT_TYPE.READ_AS_IF,
  SLOT_TYPE.GESTURE_INITIAL,
  SLOT_TYPE.READ_AS_IF,
  SLOT_TYPE.WRITE_WORD,
  SLOT_TYPE.STARTS_WITH,
  SLOT_TYPE.GESTURE_INITIAL,
  SLOT_TYPE.READ_AS_IF,
  SLOT_TYPE.DRAW_PHRASE,
  SLOT_TYPE.READ_AS_IF,
  SLOT_TYPE.STARTS_WITH,
  SLOT_TYPE.WRITE_WORD,
  SLOT_TYPE.GESTURE_INITIAL,
  SLOT_TYPE.STARTS_WITH,
  SLOT_TYPE.WRITE_WORD,
  SLOT_TYPE.STARTS_WITH,
];

export const ADVANCED_SLOT_TYPES = [
  SLOT_TYPE.CORRECT_SENTENCE,
  SLOT_TYPE.READ_AS_IF,
  SLOT_TYPE.WRITE_SENTENCE_REQUIRED,
  SLOT_TYPE.GESTURE_ADVANCED,
  SLOT_TYPE.EXPLAIN_WITHOUT_FORBIDDEN,
  SLOT_TYPE.READ_AS_IF,
  SLOT_TYPE.WRITE_SENTENCE,
  SLOT_TYPE.CORRECT_SENTENCE,
  SLOT_TYPE.GESTURE_ADVANCED,
  SLOT_TYPE.READ_AS_IF,
  SLOT_TYPE.WRITE_SENTENCE,
  SLOT_TYPE.EXPLAIN_WITHOUT_FORBIDDEN,
  SLOT_TYPE.GESTURE_ADVANCED,
  SLOT_TYPE.READ_AS_IF,
  SLOT_TYPE.CORRECT_SENTENCE,
  SLOT_TYPE.READ_AS_IF,
  SLOT_TYPE.EXPLAIN_WITHOUT_FORBIDDEN,
  SLOT_TYPE.WRITE_SENTENCE,
  SLOT_TYPE.GESTURE_ADVANCED,
  SLOT_TYPE.EXPLAIN_WITHOUT_FORBIDDEN,
  SLOT_TYPE.WRITE_SENTENCE,
  SLOT_TYPE.CORRECT_SENTENCE,
];
